/**
 * JSDump for web browsers
 * (c) Copyright 2020-present Richard Li <richard.li@w3plan.net>
 * License: MIT
 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var g=0;return function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,e){a!=Array.prototype&&a!=Object.prototype&&(a[g]=e.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.makeIterator=function(a){var g="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return g?g.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var g,e=[];!(g=a.next()).done;)e.push(g.value);return e};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.polyfill=function(a,g,e,b){if(g){e=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var d=a[b];d in e||(e[d]={});e=e[d]}a=a[a.length-1];b=e[a];g=g(b);g!=b&&null!=g&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Object.getOwnPropertySymbols",function(a){return a?a:function(){return[]}},"es6","es5");
$jscomp.polyfill("Reflect.ownKeys",function(a){return a?a:function(a){var e=[],b=Object.getOwnPropertyNames(a);a=Object.getOwnPropertySymbols(a);for(var d=0;d<b.length;d++)("jscomp_symbol_"==b[d].substring(0,14)?a:e).push(b[d]);return e.concat(a)}},"es6","es5");$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6","es3");
$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6","es3");$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6","es3");$jscomp.polyfill("Number.isSafeInteger",function(a){return a?a:function(a){return Number.isInteger(a)&&Math.abs(a)<=Number.MAX_SAFE_INTEGER}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},g=Object.create(new $jscomp.global.Proxy(a,{get:function(e,b,d){return e==a&&"q"==b&&d==g}}));return!0===g.q}catch(e){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,g){return Object.prototype.hasOwnProperty.call(a,g)};
$jscomp.polyfill("WeakMap",function(a){function g(){if(!a||!Object.seal)return!1;try{var p=Object.seal({}),f=Object.seal({}),c=new a([[p,2],[f,3]]);if(2!=c.get(p)||3!=c.get(f))return!1;c.delete(p);c.set(f,4);return!c.has(p)&&4==c.get(f)}catch(q){return!1}}function e(){}function b(a){if(!$jscomp.owns(a,l)){var f=new e;$jscomp.defineProperty(a,l,{value:f})}}function d(a){var f=Object[a];f&&(Object[a]=function(a){if(a instanceof e)return a;b(a);return f(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&
$jscomp.ES6_CONFORMANCE)return a}else if(g())return a;var l="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");var h=0,c=function(a){this.id_=(h+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var f;!(f=a.next()).done;)f=f.value,this.set(f[0],f[1])}};c.prototype.set=function(a,f){b(a);if(!$jscomp.owns(a,l))throw Error("WeakMap key fail: "+a);a[l][this.id_]=f;return this};c.prototype.get=function(a){return $jscomp.owns(a,l)?a[l][this.id_]:void 0};c.prototype.has=
function(a){return $jscomp.owns(a,l)&&$jscomp.owns(a[l],this.id_)};c.prototype.delete=function(a){return $jscomp.owns(a,l)&&$jscomp.owns(a[l],this.id_)?delete a[l][this.id_]:!1};return c},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function g(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),f=new a($jscomp.makeIterator([[c,"s"]]));if("s"!=f.get(c)||1!=f.size||f.get({x:4})||f.set({x:4},"t")!=f||2!=f.size)return!1;var b=f.entries(),h=b.next();if(h.done||h.value[0]!=c||"s"!=h.value[1])return!1;h=b.next();return h.done||4!=h.value[0].x||"t"!=h.value[1]||!b.next().done?!1:!0}catch(r){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(g())return a;$jscomp.initSymbolIterator();var e=new WeakMap,b=function(a){this.data_={};this.head_=h();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var f;!(f=a.next()).done;)f=f.value,this.set(f[0],f[1])}};b.prototype.set=function(a,f){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=f:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:f},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};b.prototype.delete=function(a){a=d(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};b.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=h();this.size=0};b.prototype.has=function(a){return!!d(this,a).entry};
b.prototype.get=function(a){return(a=d(this,a).entry)&&a.value};b.prototype.entries=function(){return l(this,function(a){return[a.key,a.value]})};b.prototype.keys=function(){return l(this,function(a){return a.key})};b.prototype.values=function(){return l(this,function(a){return a.value})};b.prototype.forEach=function(a,f){for(var c=this.entries(),h;!(h=c.next()).done;)h=h.value,a.call(f,h[1],h[0],this)};b.prototype[Symbol.iterator]=b.prototype.entries;var d=function(a,f){var h=f&&typeof f;"object"==
h||"function"==h?e.has(f)?h=e.get(f):(h=""+ ++c,e.set(f,h)):h="p_"+f;var b=a.data_[h];if(b&&$jscomp.owns(a.data_,h))for(a=0;a<b.length;a++){var d=b[a];if(f!==f&&d.key!==d.key||f===d.key)return{id:h,list:b,index:a,entry:d}}return{id:h,list:b,index:-1,entry:void 0}},l=function(a,f){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:f(c)};c=null}return{done:!0,value:void 0}})},h=function(){var a={};return a.previous=
a.next=a.head=a},c=0;return b},"es6","es3");
$jscomp.polyfill("Set",function(a){function g(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a($jscomp.makeIterator([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),h=e.next();if(h.done||h.value[0]!=b||h.value[1]!=b)return!1;h=e.next();return h.done||h.value[0]==b||4!=h.value[0].x||h.value[1]!=h.value[0]?!1:e.next().done}catch(c){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(g())return a;$jscomp.initSymbolIterator();var e=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};e.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};e.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};e.prototype.clear=function(){this.map_.clear();
this.size=0};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.entries=function(){return this.map_.entries()};e.prototype.values=function(){return this.map_.values()};e.prototype.keys=e.prototype.values;e.prototype[Symbol.iterator]=e.prototype.values;e.prototype.forEach=function(a,d){var b=this;this.map_.forEach(function(h){return a.call(d,h,h,b)})};return e},"es6","es3");
$jscomp.polyfill("WeakSet",function(a){function g(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),d=Object.seal({}),e=new a([b]);if(!e.has(b)||e.has(d))return!1;e.delete(b);e.add(d);return!e.has(b)&&e.has(d)}catch(h){return!1}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(g())return a;var e=function(a){this.map_=new WeakMap;if(a){a=$jscomp.makeIterator(a);for(var d;!(d=a.next()).done;)this.add(d.value)}};e.prototype.add=function(a){this.map_.set(a,
!0);return this};e.prototype.has=function(a){return this.map_.has(a)};e.prototype.delete=function(a){return this.map_.delete(a)};return e},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function g(){this.batch_=null}function e(a){return a instanceof d?a:new d(function(c,h){c(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;g.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};g.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var b=$jscomp.global.setTimeout;g.prototype.asyncExecuteFunction=function(a){b(a,
0)};g.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var c=0;c<a.length;++c){var d=a[c];a[c]=null;try{d()}catch(f){this.asyncThrow_(f)}}}this.batch_=null};g.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{a(c.resolve,c.reject)}catch(p){c.reject(p)}};d.prototype.createResolveAndReject_=
function(){function a(a){return function(f){d||(d=!0,a.call(c,f))}}var c=this,d=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var c=
void 0;try{c=a.then}catch(p){this.reject_(p);return}"function"==typeof c?this.settleSameAsThenable_(c,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,c){if(0!=this.state_)throw Error("Cannot settle("+a+", "+c+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=c;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)l.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var l=new g;d.prototype.settleSameAsPromise_=function(a){var c=this.createResolveAndReject_();a.callWhenSettled_(c.resolve,c.reject)};d.prototype.settleSameAsThenable_=function(a,c){var d=this.createResolveAndReject_();try{a.call(c,d.resolve,d.reject)}catch(f){d.reject(f)}};d.prototype.then=function(a,c){function e(a,c){return"function"==typeof a?function(c){try{f(a(c))}catch(t){b(t)}}:
c}var f,b,h=new d(function(a,c){f=a;b=c});this.callWhenSettled_(e(a,f),e(c,b));return h};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,c){function d(){switch(f.state_){case 1:a(f.result_);break;case 2:c(f.result_);break;default:throw Error("Unexpected state: "+f.state_);}}var f=this;null==this.onSettledCallbacks_?l.asyncExecute(d):this.onSettledCallbacks_.push(d)};d.resolve=e;d.reject=function(a){return new d(function(c,d){d(a)})};d.race=function(a){return new d(function(c,
d){for(var f=$jscomp.makeIterator(a),b=f.next();!b.done;b=f.next())e(b.value).callWhenSettled_(c,d)})};d.all=function(a){var c=$jscomp.makeIterator(a),b=c.next();return b.done?e([]):new d(function(a,d){function f(f){return function(c){r[f]=c;k--;0==k&&a(r)}}var r=[],k=0;do r.push(void 0),k++,e(b.value).callWhenSettled_(f(r.length-1),d),b=c.next();while(!b.done)})};return d},"es6","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,e){return a===e?0!==a||1/a===1/e:a!==a&&e!==e}},"es6","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,e){var b=this;b instanceof String&&(b=String(b));var d=b.length;e=e||0;for(0>e&&(e=Math.max(e+d,0));e<d;e++){var g=b[e];if(g===a||Object.is(g,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,g,e){if(null==a)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(g instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,e){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,e||0)}},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,e,b){e=null!=e?e:function(a){return a};var d=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof g){a=g.call(a);for(var h=0;!(g=a.next()).done;)d.push(e.call(b,g.value,h++))}else for(g=a.length,h=0;h<g;h++)d.push(e.call(b,a[h],h));return d}},"es6","es3");
$jscomp.iteratorFromArray=function(a,g){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,b={next:function(){if(e<a.length){var d=e++;return{value:g(d,a[d]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};$jscomp.polyfill("Array.prototype.entries",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,e){return[a,e]})}},"es6","es3");
$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,e){return e})}},"es8","es3");$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(){var a=function(){function a(a){for(var f=0;f<c.WEB_BLT_OBJS.length;f++)if(c.WEB_BLT_OBJS[f].prototype&&c.WEB_BLT_OBJS[f].prototype===a)return"Browser standard built-in object: "+c.WEB_BLT_OBJS[f].name;return!1}function d(a){var f=[];Object.isExtensible(a)&&f.push("extensible");Object.isSealed(a)&&f.push("sealed");Object.isFrozen(a)&&f.push("frozen");return f}function e(a){return g.reduce(function(f,c){c.name&&c(a)&&f.push(c.name.substring(c.name.indexOf("is")+2));return f},[])}function h(a,
b){var f=Reflect.ownKeys(a),r=c.WEB_BLT_OBJ_KEYS;Array.isArray(b)&&0<b.length&&(r=[].concat($jscomp.arrayFromIterable(new Set([].concat($jscomp.arrayFromIterable(r),$jscomp.arrayFromIterable(b))))));return f.reduce(function(f,b){if(!r.includes(b)){var k={key:b};if(b=Object.getOwnPropertyDescriptor(a,b)){var h=[];b.configurable&&h.push("configurable");b.enumerable&&h.push("enumerable");b.writable&&h.push("writable");b.get&&c.typeCheck.isFunction(b.get)&&h.push("getter");b.set&&c.typeCheck.isFunction(b.set)&&
h.push("setter");k.attributes=h;void 0!==b.value&&null!==b.value&&(c.typeCheck.isPrimitive(b.value)||(k.attributes=k.attributes.concat(d(b.value))),k.types=e(b.value),0===k.types.length&&(k.types=["Others"]),b.value.constructor&&(k.constructor=b.value.constructor.name),k.value=b.value,k.valueSerialized=!1,void 0!==b.value.prototype&&null!==b.value.prototype&&b.value.prototype.constructor&&(k.valuePrototypeConstructor=b.value.prototype.constructor.name))}f.push(k)}return f},[])}var c={WEB_BLT_OBJS:[],
WEB_BLT_OBJ_KEYS:"length name arguments caller __defineGetter__ __defineSetter__ __lookupGetter__ __lookupSetter__".split(" "),typeCheck:{isObject:function(a){return"object"===typeof a&&"Object"===Object.prototype.toString.call(a).slice(8,-1)},isEmptyObject:function(a){return"object"===typeof a&&"Object"===Object.prototype.toString.call(a).slice(8,-1)&&0===Reflect.ownKeys(a).length},isFunction:function(a){return"function"===typeof a&&"Function"===Object.prototype.toString.call(a).slice(8,-1)&&"class"!==
a.toString().substring(0,5)},isClass:function(a){return"function"===typeof a&&"Function"===Object.prototype.toString.call(a).slice(8,-1)&&"class"===a.toString().substring(0,5)},isIterableFunction:function(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolAsyncIterator();return"function"===typeof a&&"Function"===Object.prototype.toString.call(a).slice(8,-1)&&("function"===typeof a[Symbol.iterator]||"function"===typeof a[Symbol.asyncIterator])},isAnonymousFunction:function(a){return"function"===
typeof a&&"Function"===Object.prototype.toString.call(a).slice(8,-1)&&"class"!==a.toString().substring(0,5)&&""===a.name},isAnonymousClass:function(a){return"function"===typeof a&&"Function"===Object.prototype.toString.call(a).slice(8,-1)&&"class"===a.toString().substring(0,5)&&""===a.name},isArray:function(a){return Array.isArray(a)},isEmptyArray:function(a){return Array.isArray(a)&&0===a.length},isError:function(a){return a instanceof Error&&"undefined"!==typeof a.message},isPrimitive:function(a){return Object(a)!==
a},isBoolean:function(a){return"boolean"===typeof a&&!(a instanceof Boolean)},isNumber:function(a){return"number"===typeof a&&!isNaN(a)&&!(a instanceof Number)},isFloat:function(a){return"number"===typeof a&&!isNaN(a)&&!(a instanceof Number)&&0!==a%1},isInteger:function(a){return"number"===typeof a&&!isNaN(a)&&!(a instanceof Number)&&Number.isInteger(a)},isSafeInteger:function(a){return"number"===typeof a&&!isNaN(a)&&!(a instanceof Number)&&Number.isSafeInteger(a)},isString:function(a){return"string"===
typeof a&&!(a instanceof String)},isSymbol:function(a){$jscomp.initSymbol();return"symbol"===typeof a&&!(a instanceof Symbol)},isundefined:function(a){return void 0===a},isnull:function(a){return null===a},hasPrototype:function(a){return!!a.prototype},isBooleanObject:function(a){return a instanceof Boolean&&"Boolean"===Object.prototype.toString.call(a).slice(8,-1)},isNumberObject:function(a){return a instanceof Number&&"Number"===Object.prototype.toString.call(a).slice(8,-1)},isStringObject:function(a){return a instanceof
String&&"String"===Object.prototype.toString.call(a).slice(8,-1)},isSymbolObject:function(a){$jscomp.initSymbol();return a instanceof Symbol&&"Symbol"===Object.prototype.toString.call(a).slice(8,-1)},isBoxedPrimitive:function(a){return c.typeCheck.isBooleanObject(a)||c.typeCheck.isNumberObject(a)||c.typeCheck.isStringObject(a)||c.typeCheck.isSymbolObject(a)},isGeneratorObject:function(a){return"Generator"===Object.prototype.toString.call(a).slice(8,-1)},isArgumentsObject:function(a){return"Arguments"===
Object.prototype.toString.call(a).slice(8,-1)},isDate:function(a){return a instanceof Date&&"Date"===Object.prototype.toString.call(a).slice(8,-1)},isRegExp:function(a){return a instanceof RegExp&&"RegExp"===Object.prototype.toString.call(a).slice(8,-1)},isMap:function(a){return a instanceof Map&&"Map"===Object.prototype.toString.call(a).slice(8,-1)},isMapIterator:function(a){return"Map Iterator"===Object.prototype.toString.call(a).slice(8,-1)},isWeakMap:function(a){return"WeakMap"===Object.prototype.toString.call(a).slice(8,
-1)},isSet:function(a){return a instanceof Set&&"Set"===Object.prototype.toString.call(a).slice(8,-1)},isSetIterator:function(a){return"Set Iterator"===Object.prototype.toString.call(a).slice(8,-1)},isWeakSet:function(a){return"WeakSet"===Object.prototype.toString.call(a).slice(8,-1)},isPromise:function(a){return"Promise"===Object.prototype.toString.call(a).slice(8,-1)},isInt8Array:function(a){return a instanceof Int8Array&&"Int8Array"===Object.prototype.toString.call(a).slice(8,-1)},isInt16Array:function(a){return a instanceof
Int16Array&&"Int16Array"===Object.prototype.toString.call(a).slice(8,-1)},isInt32Array:function(a){return a instanceof Int32Array&&"Int32Array"===Object.prototype.toString.call(a).slice(8,-1)},isFloat32Array:function(a){return a instanceof Float32Array&&"Float32Array"===Object.prototype.toString.call(a).slice(8,-1)},isFloat64Array:function(a){return a instanceof Float64Array&&"Float64Array"===Object.prototype.toString.call(a).slice(8,-1)},isUint8Array:function(a){return a instanceof Uint8Array&&"Uint8Array"===
Object.prototype.toString.call(a).slice(8,-1)},isUint8ClampedArray:function(a){return a instanceof Uint8ClampedArray&&"Uint8ClampedArray"===Object.prototype.toString.call(a).slice(8,-1)},isUint16Array:function(a){return a instanceof Uint16Array&&"Uint16Array"===Object.prototype.toString.call(a).slice(8,-1)},isUint32Array:function(a){return a instanceof Uint32Array&&"Uint32Array"===Object.prototype.toString.call(a).slice(8,-1)},isDataView:function(a){return a instanceof DataView&&"DataView"===Object.prototype.toString.call(a).slice(8,
-1)},isAsyncFunction:function(a){return"AsyncFunction"===Object.prototype.toString.call(a).slice(8,-1)},isGeneratorFunction:function(a){return"GeneratorFunction"===Object.prototype.toString.call(a).slice(8,-1)}}},g=[c.typeCheck.isundefined,c.typeCheck.isnull,c.typeCheck.isBoolean,c.typeCheck.isNumber,c.typeCheck.isFloat,c.typeCheck.isSafeInteger,c.typeCheck.isInteger,c.typeCheck.isString,c.typeCheck.isSymbol,c.typeCheck.isPrimitive,c.typeCheck.isEmptyObject,c.typeCheck.isBooleanObject,c.typeCheck.isNumberObject,
c.typeCheck.isStringObject,c.typeCheck.isSymbolObject,c.typeCheck.isBoxedPrimitive,c.typeCheck.isGeneratorObject,c.typeCheck.isArgumentsObject,c.typeCheck.isDate,c.typeCheck.isRegExp,c.typeCheck.isEmptyArray,c.typeCheck.isArray,c.typeCheck.isMap,c.typeCheck.isMapIterator,c.typeCheck.isWeakMap,c.typeCheck.isSet,c.typeCheck.isSetIterator,c.typeCheck.isWeakSet,c.typeCheck.isPromise,c.typeCheck.isInt8Array,c.typeCheck.isInt16Array,c.typeCheck.isInt32Array,c.typeCheck.isFloat32Array,c.typeCheck.isFloat64Array,
c.typeCheck.isUint8Array,c.typeCheck.isUint8ClampedArray,c.typeCheck.isUint16Array,c.typeCheck.isUint32Array,c.typeCheck.isDataView,c.typeCheck.isAnonymousClass,c.typeCheck.isClass,c.typeCheck.isAsyncFunction,c.typeCheck.isGeneratorFunction,c.typeCheck.isIterableFunction,c.typeCheck.isAnonymousFunction,c.typeCheck.isFunction,c.typeCheck.isError,c.typeCheck.isObject];try{$jscomp.initSymbol(),c.WEB_BLT_OBJS=[Object,Function,Boolean,Symbol,Number,Date,String,RegExp,Array,Map,Set,WeakMap,WeakSet,Promise,
DataView,Int8Array,Uint8Array,Uint8ClampedArray,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,Error,EvalError,RangeError,ReferenceError,SyntaxError,TypeError,URIError,AbortSignal,AnalyserNode,Attr,Audio,AudioBuffer,AudioBufferSourceNode,AudioContext,AudioDestinationNode,AudioListener,AudioNode,AudioParam,AudioProcessingEvent,AuthenticatorAssertionResponse,AuthenticatorAttestationResponse,AuthenticatorResponse,BarProp,BeforeUnloadEvent,BiquadFilterNode,Blob,ByteLengthQueuingStrategy,
CDATASection,CSS,CSSConditionRule,CSSFontFaceRule,CSSGroupingRule,CSSImportRule,CSSKeyframeRule,CSSKeyframesRule,CSSMediaRule,CSSNamespaceRule,CSSPageRule,CSSRule,CSSRuleList,CSSStyleDeclaration,CSSStyleRule,CSSStyleSheet,CSSSupportsRule,Cache,CacheStorage,CanvasGradient,CanvasPattern,CanvasRenderingContext2D,ChannelMergerNode,ChannelSplitterNode,CharacterData,CloseEvent,Comment,CompositionEvent,ConvolverNode,CountQueuingStrategy,Credential,CredentialsContainer,Crypto,CryptoKey,CustomEvent,DOMException,
DOMImplementation,DOMParser,DOMStringList,DOMStringMap,DOMTokenList,DataTransfer,DataTransferItem,DataTransferItemList,DelayNode,Document,DocumentFragment,DocumentType,DragEvent,DynamicsCompressorNode,Element,ErrorEvent,Event,EventTarget,File,FileList,FileReader,FocusEvent,FormData,GainNode,Gamepad,GamepadButton,GamepadEvent,GamepadHapticActuator,HTMLAllCollection,HTMLAnchorElement,HTMLAreaElement,HTMLAudioElement,HTMLBRElement,HTMLBaseElement,HTMLBodyElement,HTMLButtonElement,HTMLCanvasElement,HTMLCollection,
HTMLDListElement,HTMLDataElement,HTMLDataListElement,HTMLDirectoryElement,HTMLDivElement,HTMLDocument,HTMLElement,HTMLEmbedElement,HTMLFieldSetElement,HTMLFontElement,HTMLFormControlsCollection,HTMLFormElement,HTMLFrameElement,HTMLFrameSetElement,HTMLHRElement,HTMLHeadElement,HTMLHeadingElement,HTMLHtmlElement,HTMLIFrameElement,HTMLImageElement,HTMLInputElement,HTMLLIElement,HTMLLabelElement,HTMLLegendElement,HTMLLinkElement,HTMLMapElement,HTMLMarqueeElement,HTMLMediaElement,HTMLMenuElement,HTMLMetaElement,
HTMLMeterElement,HTMLModElement,HTMLOListElement,HTMLObjectElement,HTMLOptGroupElement,HTMLOptionElement,HTMLOptionsCollection,HTMLOutputElement,HTMLParagraphElement,HTMLParamElement,HTMLPictureElement,HTMLPreElement,HTMLProgressElement,HTMLQuoteElement,HTMLScriptElement,HTMLSelectElement,HTMLSourceElement,HTMLSpanElement,HTMLStyleElement,HTMLTableCaptionElement,HTMLTableCellElement,HTMLTableColElement,HTMLTableElement,HTMLTableRowElement,HTMLTableSectionElement,HTMLTemplateElement,HTMLTextAreaElement,
HTMLTimeElement,HTMLTitleElement,HTMLTrackElement,HTMLUListElement,HTMLUnknownElement,HTMLVideoElement,HashChangeEvent,Headers,History,IDBCursor,IDBCursorWithValue,IDBDatabase,IDBFactory,IDBIndex,IDBKeyRange,IDBObjectStore,IDBOpenDBRequest,IDBRequest,IDBTransaction,IDBVersionChangeEvent,IIRFilterNode,Image,ImageData,IntersectionObserver,IntersectionObserverEntry,KeyboardEvent,Location,MediaDeviceInfo,MediaDevices,MediaElementAudioSourceNode,MediaEncryptedEvent,MediaError,MediaKeyMessageEvent,MediaKeySession,
MediaKeyStatusMap,MediaKeySystemAccess,MediaKeys,MediaList,MediaQueryList,MediaSource,MediaStream,MediaStreamEvent,MediaStreamTrack,MediaStreamTrackEvent,MessageChannel,MessageEvent,MessagePort,MimeType,MimeTypeArray,MouseEvent,MutationEvent,MutationObserver,MutationRecord,NamedNodeMap,Navigator,Node,NodeIterator,NodeList,Notification,OfflineAudioCompletionEvent,OfflineAudioContext,Option,OscillatorNode,PageTransitionEvent,PannerNode,Path2D,Performance,PerformanceEntry,PerformanceMark,PerformanceMeasure,
PerformanceNavigation,PerformanceResourceTiming,PerformanceTiming,PeriodicWave,Plugin,PluginArray,PointerEvent,PopStateEvent,ProcessingInstruction,ProgressEvent,PublicKeyCredential,PushManager,PushSubscription,PushSubscriptionOptions,RTCIceCandidate,RTCPeerConnection,RTCPeerConnectionIceEvent,RTCRtpReceiver,RTCRtpSender,RTCSessionDescription,RadioNodeList,Range,ReadableStream,Request,Response,SVGAElement,SVGAngle,SVGAnimatedAngle,SVGAnimatedBoolean,SVGAnimatedEnumeration,SVGAnimatedInteger,SVGAnimatedLength,
SVGAnimatedLengthList,SVGAnimatedNumber,SVGAnimatedNumberList,SVGAnimatedPreserveAspectRatio,SVGAnimatedRect,SVGAnimatedString,SVGAnimatedTransformList,SVGCircleElement,SVGClipPathElement,SVGComponentTransferFunctionElement,SVGDefsElement,SVGDescElement,SVGElement,SVGEllipseElement,SVGFEBlendElement,SVGFEColorMatrixElement,SVGFEComponentTransferElement,SVGFECompositeElement,SVGFEConvolveMatrixElement,SVGFEDiffuseLightingElement,SVGFEDisplacementMapElement,SVGFEDistantLightElement,SVGFEFloodElement,
SVGFEFuncAElement,SVGFEFuncBElement,SVGFEFuncGElement,SVGFEFuncRElement,SVGFEGaussianBlurElement,SVGFEImageElement,SVGFEMergeElement,SVGFEMergeNodeElement,SVGFEMorphologyElement,SVGFEOffsetElement,SVGFEPointLightElement,SVGFESpecularLightingElement,SVGFESpotLightElement,SVGFETileElement,SVGFETurbulenceElement,SVGFilterElement,SVGForeignObjectElement,SVGGElement,SVGGradientElement,SVGGraphicsElement,SVGImageElement,SVGLength,SVGLengthList,SVGLineElement,SVGLinearGradientElement,SVGMarkerElement,SVGMaskElement,
SVGMatrix,SVGMetadataElement,SVGNumber,SVGNumberList,SVGPathElement,SVGPatternElement,SVGPoint,SVGPointList,SVGPolygonElement,SVGPolylineElement,SVGPreserveAspectRatio,SVGRadialGradientElement,SVGRect,SVGRectElement,SVGSVGElement,SVGScriptElement,SVGStopElement,SVGStringList,SVGStyleElement,SVGSwitchElement,SVGSymbolElement,SVGTSpanElement,SVGTextContentElement,SVGTextElement,SVGTextPathElement,SVGTextPositioningElement,SVGTitleElement,SVGTransform,SVGTransformList,SVGUnitTypes,SVGUseElement,SVGViewElement,
Screen,ScriptProcessorNode,SecurityPolicyViolationEvent,Selection,ServiceWorker,ServiceWorkerContainer,ServiceWorkerRegistration,SourceBuffer,SourceBufferList,SpeechSynthesisEvent,SpeechSynthesisUtterance,StaticRange,StereoPannerNode,Storage,StorageEvent,StyleSheet,StyleSheetList,SubtleCrypto,Text,TextMetrics,TextTrack,TextTrackCue,TextTrackCueList,TextTrackList,TimeRanges,TrackEvent,TransitionEvent,TreeWalker,UIEvent,URL,URLSearchParams,ValidityState,VideoPlaybackQuality,WaveShaperNode,WebGLActiveInfo,
WebGLBuffer,WebGLContextEvent,WebGLFramebuffer,WebGLProgram,WebGLRenderbuffer,WebGLRenderingContext,WebGLShader,WebGLShaderPrecisionFormat,WebGLTexture,WebGLUniformLocation,WebKitCSSMatrix,WebSocket,WheelEvent,Window,Worker,XMLDocument,XMLHttpRequest,XMLHttpRequestEventTarget,XMLHttpRequestUpload,XMLSerializer,XPathEvaluator,XPathExpression,XPathResult]}catch(f){console.log("JSDump-Web requires the browser supporting for ES6 (ECMAScript 2015)")}this.entriesObj=function(b,d){d=void 0===d?[]:d;if(c.typeCheck.isPrimitive(b))return null;
var e={};e.ownEntries=h(b,d);var f=Object.getPrototypeOf(b);if(f){var k=a(f);e.inheritedEntries=k?k:h(f,d)}c.typeCheck.hasPrototype(b)&&(e.prototypeOwnEntries=h(b.prototype,d),f=Object.getPrototypeOf(b.prototype))&&(k=a(f),e.prototypeIheritedEntries=k?k:h(f,d));a:if(c.typeCheck.hasPrototype(b)){try{var n=new b}catch(t){b=void 0;break a}b=n}else b=void 0;b&&(e.instanceOwnEntries=h(b,d));return e}},g=function(){function a(a){return q[a]}var d=Math.floor(1099511627776*Math.random()).toString(16),e=new RegExp('"@__(F|R|D|M|S|U|I)-'+
d+'-(\\d+)__@"',"g"),h=/\{\s*\[native code\]\s*\}/g,c=/function.*?\(/,g=/.*?=>.*?/,f=/[<>\/\u2028\u2029]/g,u=["*","async"],q={"<":"\\u003C",">":"\\u003E","/":"\\u002F","\u2028":"\\u2028","\u2029":"\\u2029"};return function t(b,n){function k(a,c){if(n.ignoreFunction){var b=[],e;for(e in c)"function"===typeof c[e]&&b.push(e);for(e=0;e<b.length;e++)delete c[b[e]]}if(!c&&void 0!==c)return c;a=this[a];b=typeof a;if("object"===b){if(a instanceof RegExp)return"@__R-"+d+"-"+(m.push(a)-1)+"__@";if(a instanceof
Date)return"@__D-"+d+"-"+(x.push(a)-1)+"__@";if(a instanceof Map)return"@__M-"+d+"-"+(y.push(a)-1)+"__@";if(a instanceof Set)return"@__S-"+d+"-"+(z.push(a)-1)+"__@"}return"function"===b?"@__F-"+d+"-"+(v.push(a)-1)+"__@":"undefined"===b?"@__U-"+d+"-"+(l.push(a)-1)+"__@":"number"!==b||isNaN(a)||isFinite(a)?c:"@__I-"+d+"-"+(A.push(a)-1)+"__@"}function B(a){var b=a.toString();if(h.test(b))throw new TypeError("Serializing native function: "+a.name);if(c.test(b)||g.test(b))return b;a=b.indexOf("(");var d=
b.substr(0,a).trim().split(" ").filter(function(a){return 0<a.length});return 0<d.filter(function(a){return-1===u.indexOf(a)}).length?(-1<d.indexOf("async")?"async ":"")+"function"+(-1<d.join("").indexOf("*")?"*":"")+b.substr(a):b}n||(n={});if("number"===typeof n||"string"===typeof n)n={space:n};var v=[],m=[],x=[],y=[],z=[],l=[],A=[];n.ignoreFunction&&"function"===typeof b&&(b=void 0);if(void 0===b)return String(b);b=n.isJSON&&!n.space?JSON.stringify(b):JSON.stringify(b,n.isJSON?null:k,n.space);if("string"!==
typeof b)return String(b);!0!==n.unsafe&&(b=b.replace(f,a));return 0===v.length&&0===m.length&&0===x.length&&0===y.length&&0===z.length&&0===l.length&&0===A.length?b:b.replace(e,function(a,c,b){return"D"===c?'new Date("'+x[b].toISOString()+'")':"R"===c?"new RegExp("+t(m[b].source)+', "'+m[b].flags+'")':"M"===c?"new Map("+t(Array.from(y[b].entries()),n)+")":"S"===c?"new Set("+t(Array.from(z[b].values()),n)+")":"U"===c?"undefined":"I"===c?A[b]:B(v[b])})}},e=function(){function a(a,c){var b={seen:[],
stylize:d};3<=arguments.length&&(b.depth=arguments[2]);4<=arguments.length&&(b.colors=arguments[3]);if("boolean"===typeof c)b.showHidden=c;else if(c&&c&&g(c))for(var f=Object.keys(c),m=f.length;m--;)b[f[m]]=c[f[m]];void 0===b.showHidden&&(b.showHidden=!1);void 0===b.depth&&(b.depth=2);void 0===b.colors&&(b.colors=!1);void 0===b.customInspect&&(b.customInspect=!0);b.colors&&(b.stylize=e);return n(b,a,b.depth)}function d(a,c){return a}function e(c,b){return(b=a.styles[b])?"\u001b["+a.colors[b][0]+"m"+
c+"\u001b["+a.colors[b][1]+"m":c}function h(a){return"function"===typeof a}function c(a){return g(a)&&"[object RegExp]"===Object.prototype.toString.call(a)}function g(a){return"object"===typeof a&&null!==a}function f(a){return g(a)&&("[object Error]"===Object.prototype.toString.call(a)||a instanceof Error)}function u(a){return g(a)&&"[object Date]"===Object.prototype.toString.call(a)}function q(a){var c={};a.forEach(function(a,b){c[a]=!0});return c}function r(a,c,b,d,e){for(var f=[],m=0,k=c.length;m<
k;++m)Object.prototype.hasOwnProperty.call(c,String(m))?f.push(t(a,c,b,d,String(m),!0)):f.push("");e.forEach(function(e){e.match(/^\d+$/)||f.push(t(a,c,b,d,e,!0))});return f}function k(a){return"["+Error.prototype.toString.call(a)+"]"}function n(b,d,e){if(b.customInspect&&d&&h(d.inspect)&&d.inspect!==a&&(!d.constructor||d.constructor.prototype!==d)){var g=d.inspect(e,b);"string"!==typeof g&&(g=n(b,g,e));return g}if(g=C(b,d))return g;var m=Object.keys(d),v=q(m);try{b.showHidden&&Object.getOwnPropertyNames&&
(m=Object.getOwnPropertyNames(d))}catch(E){}if(f(d)&&(0<=m.indexOf("message")||0<=m.indexOf("description")))return k(d);if(0===m.length){if(h(d))return b.stylize("[Function"+(d.name?": "+d.name:"")+"]","special");if(c(d))return b.stylize(RegExp.prototype.toString.call(d),"regexp");if(u(d))return b.stylize(Date.prototype.toString.call(d),"date");if(f(d))return k(d)}g="";var l=!1,w=["{","}"];Array.isArray(d)&&(l=!0,w=["[","]"]);h(d)&&(g=" [Function"+(d.name?": "+d.name:"")+"]");c(d)&&(g=" "+RegExp.prototype.toString.call(d));
u(d)&&(g=" "+Date.prototype.toUTCString.call(d));f(d)&&(g=" "+k(d));if(0===m.length&&(!l||0==d.length))return w[0]+g+w[1];if(0>e)return c(d)?b.stylize(RegExp.prototype.toString.call(d),"regexp"):b.stylize("[Object]","special");b.seen.push(d);m=l?r(b,d,e,v,m):m.map(function(a){return t(b,d,e,v,a,l)});b.seen.pop();return B(m,g,w)}function t(a,b,c,d,e,f){var k,g;var h={value:void 0};try{h.value=b[e]}catch(D){}try{Object.getOwnPropertyDescriptor&&(h=Object.getOwnPropertyDescriptor(b,e)||h)}catch(D){}h.get?
g=h.set?a.stylize("[Getter/Setter]","special"):a.stylize("[Getter]","special"):h.set&&(g=a.stylize("[Setter]","special"));Object.prototype.hasOwnProperty.call(d,e)||(k="["+e+"]");g||(0>a.seen.indexOf(h.value)?(g=null===c?n(a,h.value,null):n(a,h.value,c-1),-1<g.indexOf("\n")&&(g=f?g.split("\n").map(function(a){return"  "+a}).join("\n").substr(2):"\n"+g.split("\n").map(function(a){return"   "+a}).join("\n"))):g=a.stylize("[Circular]","special"));if(void 0===k){if(f&&e.match(/^\d+$/))return g;k=JSON.stringify(""+
e);k.match(/^"([a-zA-Z_][a-zA-Z_0-9]*)"$/)?(k=k.substr(1,k.length-2),k=a.stylize(k,"name")):(k=k.replace(/'/g,"\\'").replace(/\\"/g,'"').replace(/(^"|"$)/g,"'"),k=a.stylize(k,"string"))}return k+": "+g}function C(a,b){if(void 0===b)return a.stylize("undefined","undefined");if("string"===typeof b)return b="'"+JSON.stringify(b).replace(/^"|"$/g,"").replace(/'/g,"\\'").replace(/\\"/g,'"')+"'",a.stylize(b,"string");if("number"===typeof b)return a.stylize(""+b,"number");if("boolean"===typeof b)return a.stylize(""+
b,"boolean");if(null===b)return a.stylize("null","null")}function B(a,b,c){var d=0;return 60<a.reduce(function(a,b){d++;0<=b.indexOf("\n")&&d++;return a+b.replace(/\u001b\[\d\d?m/g,"").length+1},0)?c[0]+(""===b?"":b+"\n ")+" "+a.join(",\n  ")+" "+c[1]:c[0]+b+" "+a.join(", ")+" "+c[1]}a.colors={bold:[1,22],italic:[3,23],underline:[4,24],inverse:[7,27],white:[37,39],grey:[90,39],black:[30,39],blue:[34,39],cyan:[36,39],green:[32,39],magenta:[35,39],red:[31,39],yellow:[33,39]};a.styles={special:"blue",
number:"magenta","boolean":"magenta",undefined:"grey","null":"bold",string:"green",date:"magenta",regexp:"red"};return a};window.jsdump=new function(b){function d(a){a.forEach(function(b,c){if(b.value&&!b.types.includes("Primitive")&&!b.types.includes("BoxedPrimitive"))try{a[c].value=u(b.value),a[c].valueSerialized=!0}catch(t){}});return a}function l(a,b){var c="",d="\n",e="",f="";p.forEach(function(g){a&&a.hasOwnProperty(g)&&(f=a[g],Array.isArray(f)&&0<f.length&&f.forEach(function(a){if(void 0!==
a.value&&b&&a.key===b)if(a.types.includes("Primitive")||a.types.includes("BoxedPrimitive"))c+=d+a.value;else try{e=u(a.value),a.types.includes("Class")&&void 0!==a.valuePrototypeConstructor&&"constructor"===b&&(d="\nclass "+a.valuePrototypeConstructor+" {  ",e=e.replace(/^function/,"[function]").replace(new RegExp("^class "+a.valuePrototypeConstructor+" +{"),"")),c+=d+e}catch(x){c+=d+"The native code can't be dumped out."}}))});return c}function h(a,b,c){var d=null;"primitive function class indexedCollection keyedCollection others".split(" ").includes(c)||
(c="function");p.forEach(function(e){if(a&&a.hasOwnProperty(e)&&(d=a[e],Array.isArray(d)&&0<d.length))for(e=0;e<d.length;e++)if(Array.isArray(d[e].types)&&0<d[e].types.length)for(var g=0;g<d[e].types.length;g++)if(f[c].includes(d[e].types[g])){b.push(d[e]);break}});return b}function c(a,b){var c=window.open("","JSDump-Web","menubar=yes,location=yes,resizable=yes,scrollbars=yes,status=yes"),d='<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>JSDump-Web</title></head><body>'+
a+"</body></html>";b||(d='<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><title>JSDump-Web</title><style>body,.w3-container{width:94%;margin-left:3%;}.w3-container:after,.w3-container:before,.w3-panel:after,.w3-panel:before,.w3-row:after,.w3-row:before,.w3-row-padding:after,.w3-row-padding:before,.w3-cell-row:before,.w3-cell-row:after,.w3-clear:after,.w3-clear:before,.w3-bar:before,.w3-bar:after{content:"";display:table;clear:both}.w3-section,.w3-code{margin-top:16px!important;margin-bottom:16px!important}.w3-grey,.w3-hover-grey:hover,.w3-gray,.w3-hover-gray:hover{color:#000!important;background-color:#9e9e9e!important}.w3-card-4,.w3-hover-shadow:hover{box-shadow:0 4px 10px 0 rgba(0,0,0,0.2),0 4px 20px 0 rgba(0,0,0,0.19)}.w3-white,.w3-hover-white:hover{color:#000!important;background-color:#fff!important}.w3-large{font-size:18px!important}.w3-text-white,.w3-hover-text-white:hover{color:#fff!important}.language-js{white-space:pre-wrap}</style></head><body>'+
a+'</body><footer class="w3-container"><p style="text-align:right">Powered by JSDump-Web</p></footer></html>');c.document.write(d);c.document.close()}this.NAME="JSDump-Web";this.DESCRIPTION="JSDump for web browser "+b;var p=["ownEntries","inheritedEntries","prototypeOwnEntries","prototypeIheritedEntries","instanceOwnEntries"],f={primitive:"undefined null Boolean Number Float SafeInteger Integer BigInt String Symbol".split(" "),function:["AsyncFunction","GeneratorFunction","IterableFunction","AnonymousFunction",
"Function"],class:["AnonymousClass","Class"],indexedCollection:"EmptyArray Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array BigInt64Array BigUint64Array".split(" "),keyedCollection:["Map","Set","WeakMap","WeakSet"],others:"EmptyObject BooleanObject NumberObject StringObject SymbolObject BoxedPrimitive GeneratorObject ArgumentsObject ModuleNamespaceObject Object Date RegExp MapIterator SetIterator Promise Proxy SharedArrayBuffer AnyArrayBuffer ArrayBuffer Buffer DataView NativeError Error External Others".split(" ")},
u=g(),q=e();a.apply(this,arguments);this.info=function(){console.log("\n       ***  JSDump-Web ***\n    JSDump-Web is a tool to dump out the information of own and inherited properties from an object, \n    object prototype, and object instance.\n    \n    JSDump-Web is a version of JSDump specified for web browsers.\n    \n    Sample Usage:\n      // prints this message.\n      jsdump.info();\n      // returns an object that includes dumped out content from URL.\n      jsdump.entriesObj(URL);\n      \n      // prints the information of URL to the console.\n      jsdump.entriesPrint(URL);\n      \n      // writes the information of URL to a new page.\n      jsdump.entriesPage(URL);\n      // writes the information of URL without style to a new page.\n      jsdump.entriesPage(URL, true);\n      \n      // prints the information of entries type with 'function' from URL to the console.\n      jsdump.typeEntriesPrint(URL);\n      \n      // writes the serialized information of entries type with 'function' from URL to new page.\n      jsdump.typeEntriesPage(URL);\n      \n      // prints constructor source of jsdump to the console.\n      jsdump.sourcePrint(jsdump);\n      // prints sourcePrint source of jsdump to the console.\n      jsdump.sourcePrint(jsdump, 'sourcePrint');\n      \n      // writes raw constructor of jsdump to a new page.\n      jsdump.sourcePage(jsdump, 'constructor', true);\n      // writes sourcePrint source of jsdump to a new page.\n      jsdump.sourcePage(jsdump, 'sourcePrint');\n    \n    Author: Richard Li <richard.li@w3plan.net>, License: MIT\n    ")};
this.sourcePrint=function(a,b){b=void 0===b?"constructor":b;a=this.entriesObj(a);null===a?a="null":(a=l(a,b),0===a.length&&(a="The property: "+b+" doesn't exist."));console.log(a)};this.sourcePage=function(a,b,d){b=void 0===b?"constructor":b;d=void 0===d?!1:d;a=this.entriesObj(a);null===a?console.log("null"):(a=l(a,b),0===a.length?a="The property: "+b+" doesn't exist.":(c(d?'<pre style="white-space:pre-wrap"><code>'+a+"</code></pre>":'<div class="w3-section w3-container"><div class="w3-card-4"><div class="w3-container w3-white"><pre class="language-js"><code>'+
a+"</code></pre></div></div></div>",d),a="Printed the property source to the new page."),console.log(a))};this.entriesPrint=function(a,b,c){b=void 0===b?[]:b;c=void 0===c?!1:c;var e=null,f=!1,g="",h=this.entriesObj(a,b);null===h?g="null":(p.forEach(function(a){h&&h.hasOwnProperty(a)&&(e=h[a],Array.isArray(e)&&0<e.length&&(e=d(e)),c?(console.log("\n%c"+a,"font-weight:bold"),console.log(q(e,!1,10,!0,!0,!0))):(console.log("\n"+a),console.log(q(e,!1,10,!1,!0,!0))),f=!0)}),f||(g="There is no entries to output."));
console.log(g)};this.typeEntriesPrint=function(a,b,c,e){b=void 0===b?"function":b;c=void 0===c?[]:c;e=void 0===e?!1:e;var f=[];a=this.entriesObj(a,c);null===a?console.log("null"):(f=h(a,f,b),0===f.length?console.log("There is no entries to print."):(f=d(f),e?console.log(q(f,!1,10,!0,!0,!0)):console.log(q(f,!1,10,!1,!0,!0))))};this.entriesPage=function(a,b,e){b=void 0===b?!1:b;e=void 0===e?[]:e;var f=null,g=!1,h="",k=this.entriesObj(a,e);null===k?console.log("null"):(p.forEach(function(a){k&&k.hasOwnProperty(a)&&
(f=k[a],Array.isArray(f)&&0<f.length&&(f=d(f)),b?(h+='<p style="font-weight:bold">'+a+"</p>",h+='<pre style="white-space:pre-wrap"><code>'+q(f,!1,10,!1,!0,!0)+"</code></pre>"):(h+='<div class="w3-container w3-grey" style="position:relative"><p class="w3-large w3-text-white" style="margin-left:20px;ext-shadow:1px 1px 0 #444">'+a+"</p></div>",h+='<div class="w3-section w3-container"><div class="w3-card-4"><div class="w3-container w3-white"><pre class="language-js"><code>'+q(f,!1,10,!1,!0,!0)+"</code></pre></div></div></div>"),
g=!0)}),g?(c(h,b),h="Printed the infomation of an entries object to the new page."):h="There is no entries to output.",console.log(h))};this.typeEntriesPage=function(a,b,e,f){b=void 0===b?"function":b;e=void 0===e?!1:e;f=void 0===f?[]:f;var g=[],k="";a=this.entriesObj(a,f);if(null===a)console.log("null");else{g=h(a,g,b);if(0===g.length)k="There is no entries to print.";else{g=d(g);for(b=0;b<g.length;b++)k=e?k+('<pre style="white-space:pre-wrap"><code>'+q(g[b],!1,10,!1,!0,!0)+"</code></pre>"):k+('<div class="w3-section w3-container"><div class="w3-card-4"><div class="w3-container w3-white"><pre class="language-js"><code>'+
q(g[b],!1,10,!1,!0,!0)+"</code></pre></div></div></div>");c(k,e);k="Printed the property source to the new page."}console.log(k)}}}("Version 1.0.3")})();
